import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import config

load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

def synthesize(problem: str, bridges: list[dict], decomposed: dict) -> str:
    """
    Synthesizes multiple bridge hypotheses into a final structured report.
    
    Args:
        problem (str): The original problem description.
        bridges (list[dict]): A list of hypothesis bridges generated by the engine.
        decomposed (dict): The original decomposed structure of the problem.
        
    Returns:
        str: A final markdown report summarizing all insights and recommendations.
    """
    llm = ChatGroq(model=config.LLM_MODEL, groq_api_key=GROQ_API_KEY)
    
    system_prompt = """You are the Lead Synthesizer for the Nexus Insight Engine. 
Your goal is to merge diverse cross-domain hypotheses into a single, high-impact strategic report.

PROBLEM: {problem}
DECOMPOSED STRUCTURE: {decomposed}
BRIDGE HYPOTHESES: {bridges}

OUTPUT FORMAT:
Return a beautifully formatted Markdown report with these sections:
## The Problem
## Structural Essence
## Cross-Domain Insights
(One subsection per hypothesis with full details: core insight, steps, novelty, feasibility)
## Recommended Approach
(Rank the top 2 solutions by calculating Novelty × Feasibility and explain why)
## Why These Are Non-Obvious
## Next Steps
"""

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("user", "Generate the final synthesis report.")
    ])
    
    chain = prompt | llm | StrOutputParser()
    
    try:
        return chain.invoke({
            "problem": problem,
            "bridges": bridges,
            "decomposed": decomposed
        })
    except Exception as e:
        return f"Error during synthesis: {e}"

if __name__ == "__main__":
    print(synthesize("Misinformation", [{"hypothesis_title": "The Immune Response"}], {"essence": "Propagation"}))
